//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vido.Parking
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryExit
    {
        public int EntryExitId { get; set; }
        public string CardId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string EntryPlateNumber { get; set; }
        public string EntryTime { get; set; }
        public string EntryBackImage { get; set; }
        public string EntryFrontImage { get; set; }
        public string ExitPlateNumber { get; set; }
        public string ExitTime { get; set; }
        public string ExitBackImage { get; set; }
        public string ExitFrontImage { get; set; }
    
        public virtual Card Card { get; set; }
    }
}
