//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vido.Parking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public Card()
        {
            this.Employee = new HashSet<Employee>();
            this.InOutRecord = new HashSet<InOutRecord>();
        }
    
        public string CardId { get; set; }
        public string Data { get; set; }
        public string Type { get; set; }
        public Nullable<long> State { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<InOutRecord> InOutRecord { get; set; }
    }
}
