//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vido.Parking.Core.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public string CardId { get; set; }
        public Nullable<long> CardTypeId { get; set; }
        public Nullable<decimal> IsUse { get; set; }
    
        public virtual CardType CardType { get; set; }
    }
}
