//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vido.Parking.Core.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryExit
    {
        public string CardId { get; set; }
        public string EntryPlateNumber { get; set; }
        public string EntryTime { get; set; }
        public string EntryPlateImage { get; set; }
        public string EntryFaceImage { get; set; }
        public string ExitPlateNumber { get; set; }
        public string ExitTime { get; set; }
        public string ExitPlateImage { get; set; }
        public string ExitFaceImage { get; set; }
    }
}
