//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vido.Parking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.InOutRecord = new HashSet<InOutRecord>();
            this.InOutRecord1 = new HashSet<InOutRecord>();
        }
    
        public string EmployeeId { get; set; }
        public string CardId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual ICollection<InOutRecord> InOutRecord { get; set; }
        public virtual ICollection<InOutRecord> InOutRecord1 { get; set; }
    }
}
